const songList = [
  "箏_周治平.txt"
  ,"駅_竹内まりや.txt"
  ,"謎_蔡藍欽.txt"
  ,"卸粧_金素梅.txt"
  ,"Back For Good_Take That.txt"
  ,"Crying In The Rain_A-Ha.txt"
  ,"Do Not Go Gentle Into That Good Night_Dylan Thomas.txt"
  ,"Don't Know Why_Unnamed Artist.txt"
  ,"Dont Cry_Guns N' Roses.txt"
  ,"Dont Know Much_Linda Ronstadt.txt"
  ,"Dont Know Why_Norah Jones.txt"
  ,"Dreams_The Cranberries.txt"
  ,"Englishman In New York_Sting.txt"
  ,"Everytime We Touch_Cascada.txt"
  ,"Famous Blue Raincoat_Leonard Cohen.txt"
  ,"Home_Unnamed Artist.txt"
  ,"Honesty_Billy Joel.txt"
  ,"I Need To Be In Love_Carpenters.txt"
  ,"Let It Be_The Beatles.txt"
  ,"Love Will Keep Us Alive_Eagles.txt"
  ,"Moon Veil_Raselhits.txt"
  ,"Remember_Sam Ock.txt"
  ,"Run For The Roses_Dan Fogelberg.txt"
  ,"Shape Of My Heart_Sting.txt"
  ,"Thats Why_Michael Learns To Rock.txt"
  ,"The Best Of Me_David Foster.txt"
  ,"The Girl With April In Her Eyes_Chris De Burgh.txt"
  ,"Unnamed Song_Unnamed Artist.txt"
  ,"Until I Found You_Stephen Sanchez.txt"
  ,"Vincent_Don Mclean.txt"
  ,"Wicked Game_Chris Isaak.txt"
  ,"You Are The Reason_Calum Scott.txt"
  ,"一個人生活_林凡.txt"
  ,"一千個傷心的理由_張學友.txt"
  ,"一次幸福的機會_劉若英.txt"
  ,"三個人的晚餐_王若琳.txt"
  ,"下午的一齣戲_陳明章.txt"
  ,"不再讓你孤單_Unnamed Artist.txt"
  ,"不知所措_林志炫.txt"
  ,"不該認真_潘協慶.txt"
  ,"人生的歌_黃乙玲.txt"
  ,"人間_Unnamed Artist.txt"
  ,"他和她_蔡淳佳.txt"
  ,"休息_以莉‧高露.txt"
  ,"你依然在我心深處_胡瓜.txt"
  ,"你在我心中最深的地方_Unnamed Artist.txt"
  ,"偶遇_潘越雲.txt"
  ,"偶陣雨_梁靜茹.txt"
  ,"像我這樣的人_姜育恆.txt"
  ,"冬季到臺北來看雨_周蕙.txt"
  ,"冬季到臺北來看雨_孟庭葦.txt"
  ,"冷井情深_林良樂.txt"
  ,"出賣_周傳雄.txt"
  ,"別讓我心疼_鄭中基.txt"
  ,"千本櫻_和樂器樂團.txt"
  ,"去海邊 The Room By The Sea_鄭興.txt"
  ,"可惜不是你_梁靜茹.txt"
  ,"台北下的雨 Rain In Taipei_鄭興.txt"
  ,"同類_孫燕姿.txt"
  ,"告別的練習_鄭興.txt"
  ,"告白氣球_周杰倫.txt"
  ,"哭砂_黃鶯鶯.txt"
  ,"喜歡寂寞_蘇打綠.txt"
  ,"單身情歌_林志炫.txt"
  ,"困砂_方文琳.txt"
  ,"城市燈火_Unnamed Artist.txt"
  ,"夢一場_夢一場.txt"
  ,"夢不到你_夢不到你.txt"
  ,"天后_陳勢安.txt"
  ,"天際_姜玉陽.txt"
  ,"好久不見_陳奕迅.txt"
  ,"好朋友只是朋友_喻可唯.txt"
  ,"如你一般的人_陶晶瑩.txt"
  ,"如果有一天_梁靜茹.txt"
  ,"如果沒有你_莫文蔚.txt"
  ,"橘子汽水_Unnamed Artist.txt"
  ,"孤單心事_藍又時.txt"
  ,"守候_高慧君.txt"
  ,"客途秋恨_Unnamed Artist.txt"
  ,"尋你_遊鴻明.txt"
  ,"對不起我愛你_梁靜茹.txt"
  ,"平凡甲平安_曾心梅.txt"
  ,"幸福路上_蔡依林.txt"
  ,"心牆_林俊杰.txt"
  ,"情歌_梁靜茹.txt"
  ,"想你是臨睡的習慣_動力火車.txt"
  ,"想念_袁惟仁.txt"
  ,"愛上你是一個錯_楊培安.txt"
  ,"愛久見人心_梁靜茹.txt"
  ,"愛了很久的朋友_Unnamed Artist.txt"
  ,"愛情釀的酒_紅螞蟻.txt"
  ,"愛情證書_孫燕姿.txt"
  ,"愛情轉移_陳奕迅.txt"
  ,"愛的可能_葉蒨文.txt"
  ,"我不難過_孫燕姿.txt"
  ,"我們的總和_艾怡良.txt"
  ,"我們這裏還有魚_Unnamed Artist.txt"
  ,"我就在你身邊_周治平.txt"
  ,"我懷念的_孫燕姿.txt"
  ,"我等到花兒也謝了_張學友.txt"
  ,"我等的那個人 Waiting_鄭興.txt"
  ,"斷點_張敬軒.txt"
  ,"旅行的意義_陳綺貞.txt"
  ,"春泥_庾澄慶.txt"
  ,"會呼吸的痛_Fish Leong (梁靜茹).txt"
  ,"有一種悲傷_Alin.txt"
  ,"有一種愛叫做放手_阿木.txt"
  ,"末班車_蕭煌奇.txt"
  ,"江南_林俊杰.txt"
  ,"沒那麼簡單_黃小琥.txt"
  ,"沙子_周治平.txt"
  ,"滾滾紅塵_陳淑樺.txt"
  ,"漠河舞廳_柳爽.txt"
  ,"猜不透_丁當.txt"
  ,"白目_草屯.txt"
  ,"童話_辛曉琪.txt"
  ,"第一滴淚_動力火車.txt"
  ,"聽海_張惠妹.txt"
  ,"至少還有你_林憶蓮.txt"
  ,"花若離枝_江蕙.txt"
  ,"花開花謝_周治平.txt"
  ,"隕落_Unnamed Artist.txt"
  ,"記念_蔡健雅.txt"
  ,"說謊_張信哲.txt"
  ,"車窗外_許常德.txt"
  ,"返來阮身邊_江蕙.txt"
  ,"這裡離家有多遠_秀蘭瑪雅.txt"
  ,"連名帶姓_A-Mei (張惠妹).txt"
  ,"還是會寂寞_陳綺貞.txt"
  ,"那一場風花雪月的事_周治平.txt"
  ,"鐵窗_許美靜.txt"
  ,"開始懂了_孫燕姿.txt"
  ,"陪你到天亮_Phil Chang (張宇).txt"
  ,"隱形人_孫燕姿.txt"
  ,"離人_林志炫.txt"
  ,"雨蝶_李翊君.txt"
  ,"魔幻季節_梁詠琪.txt"
  ,"鱷魚的眼淚_林志炫.txt"
  ,"黑咖啡_江蕙.txt"
];
